name: Schachtraining Lübeck
favicon: null
layout_spectrum: 0.7951391346286982
typography_spectrum: 0.37575927609577775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9494407782331109
  lightness: 0.3690569626633078
  saturation: 0.21597548318095505
  rhythmicContrast: 0.09293940896168351
purpose: []
