name: Schachtraining Lübeck
favicon: null
layout_spectrum: 0.09102
typography_spectrum: 0.69384
title: Marco Frohberg - Schachtrainer
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fee6cc'
    - '#0d1723'
    - '#f2c165'
    - '#1e4c42'
    - '#b8854c'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
