name: Schachtraining Lübeck
favicon: null
layout_spectrum: 0.24483
typography_spectrum: 0.69384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d4d0cd'
    - '#000000'
    - '#4e424c'
    - '#897576'
  brandStrength: 0.4375
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
